version: "3"

services:
  test:
    image: 8e65a3bf0ba1
    privileged: true
    command: /sbin/init
    environment:
      - "TZ=Asia/Tokyo"
      - "LANG=ja_JP.UTF-8"
      - "LANGUAGE=ja_JP.UTF-8"
      - "LC_ALL=ja_JP.UTF-8"
      - "API_SERVER_URL=http://localhost/api"
      - "API_CLIENT_URL=http://localhost:50080/api"
    ports:
      - "50080:80"
    volumes:
      - ./:/var/www/liverepo-demo/current